In [1]:
import pandas as pd

In [ ]:
data = pd.read_csv("bronze/Dados_Betfair_Exchange.csv", sep=";")

# Selecinor Time Home
data = data[data["Home"] == "2 de Mayo"]

hthomegoals = data[["Home", "Goals_H_HT", "Goals_A_HT"]]

team_stats = hthomegoals.groupby("Home").agg(
    total_jogos=("Goals_H_HT", "count"),
    total_gols=("Goals_H_HT", "sum"),
    media_gols=("Goals_H_HT", "mean"),
    acima_05=("Goals_H_HT", lambda x: (x > 0.5).sum()),
    acima_15=("Goals_H_HT", lambda x: (x > 1.5).sum()),
    max_gols=("Goals_H_HT", "max"),
    min_gols=("Goals_H_HT", "min")
).reset_index()

team_stats

,Home,total_jogos,total_gols,media_gols,acima_05,acima_15,max_gols,min_gols
0,2 de Mayo,5,3,0.6,3,0,1,0

In [16]:
data2 = data = pd.read_csv("bronze/Dados_Betfair_Exchange.csv", sep=";")

data2 = data[data["Home"] == "2 de Mayo"]

data2 = data2[["Home", "Goals_H_HT", "Goals_A_HT"]]

data2

            Home  Goals_H_HT  Goals_A_HT
3513   2 de Mayo           1           0
8805   2 de Mayo           1           1
11560  2 de Mayo           1           0
12266  2 de Mayo           0           1
18421  2 de Mayo           0           1